### Exercícios NumPy

In [64]:
import numpy as np

**1.** Crie um array com 6 elementos em que os elementos possuem o padrão a seguir: 

```
[0 2 4 6 8 10]
```

In [21]:
##################
# YOUR CODE HERE.#
##################

[ 0  2  4  6  8 10]


**2.** Crie um array $3 \times 4$ com o seguinte padrão:

```
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
 ```

In [29]:
##################
# YOUR CODE HERE.#
##################

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


**3.** Crie um array $7\times7$ no qual todos os elementos têm valor 0, exceto os da linha 3 e da coluna 3, que têm valor 1, como a seguir:

```
[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]
```

In [30]:
##################
# YOUR CODE HERE.#
##################

[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]


**4.** Crie um array $5 \times 5$ com o seguinte padrão:

```
[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]
```

In [65]:
##################
# YOUR CODE HERE.#
##################

[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]


**5.** Crie um array $5 \times 5$ com o seguinte padrão:

```
[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
```

Utilize as funções `np.diag` e `np.arange`.

In [70]:
##################
# YOUR CODE HERE.#
##################

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]


**6.** Crie um array $3\times2\times4$ onde o elemento de índice $(i, j, k)$ tem valor $i^2$ para qualquer $j, k$, como abaixo:

```
[[[0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[4 4 4 4]
  [4 4 4 4]]]
```

Dica: utilize a função `np.indices`.

In [32]:
##################
# YOUR CODE HERE.#
##################

[[[0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[4 4 4 4]
  [4 4 4 4]]]


**7.** Crie um array $5\times5$ onde o elemento de índice $(i,j)$ tem valor $i^2 + j^2$.

Dica: utilize a função `np.indices`.

In [72]:
##################
# YOUR CODE HERE.#
##################

[[ 0  1  4  9 16]
 [ 1  2  5 10 17]
 [ 4  5  8 13 20]
 [ 9 10 13 18 25]
 [16 17 20 25 32]]


**8.** Gere uma matriz $10\times10$ de números aleatórios com distribuição normal de média 0 e desvio padrão 1. Calcule o *máximo* valor em cada linha e o *mínimo* valor em cada coluna.

Dica: utilize a função `np.randn`.

In [45]:
##################
# YOUR CODE HERE.#
##################

[1.54475874 1.32678088 1.34767753 1.20799757 1.97300465 2.56025928
 1.77394772 2.35946923 1.68157359 0.27578482]
[-1.28599596 -2.03253366 -1.93264582 -0.70177924 -2.88867232 -1.63482674
 -0.46286222 -2.13983684 -2.70500077 -0.55829481]


**9.** Gere uma matriz $X \in \mathbb{R}^{5\times5}$ de números aleatórios com distribuição normal de média 1 e desvio padrão 3, isto é, $X \sim \text{N}(1, 3)$. Depois gere uma matriz $Y$ de mesmo formato cujo elemento $(i,j)$ terá valor $1$ se o elemento $(i,j)$ da matriz aleatória for menor que -5 ou maior do que 7, e zero caso contrário.
Conte o número de valores diferentes de zero nessa nova matriz.

Dica: se $X \sim \text{N}(0, 1)$, então $(\sigma \cdot X + \mu) \sim \text{N}(\mu, \sigma)$.

In [75]:
##################
# YOUR CODE HERE.#
##################

[[-1.2772413   1.960622    3.83399806 -5.80812249  2.20111944]
 [-0.49420151 -3.26140988  8.04816353  0.83190964  2.26603519]
 [ 1.51355284  2.3337053   2.70260824  1.36163964 -0.68243152]
 [-0.34654622 -0.54958628 -8.67877437  5.08279659  3.51506004]
 [ 1.91338874  0.69943562  5.03726642  6.21935541 -4.12525651]]
[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


**10.** Use as regras de *broadcast* em seu benefício para gerar uma matriz $5\times5$ cujos elementos $(i,j)$ têm valor $i$. Faça o mesmo para gerar uma outra matriz de mesmo tamanho cujos elementos $(i,j)$ tenham valor $j$. Por fim, combine isso para gerar uma matriz também $5\times5$ cujos elementos $(i,j)$ tenham valor $2 i - j$.

Atenção: não utilizar `np.indices`.
Dica: utilizar soma com matriz de zeros com dimensões $10\times10$

In [76]:
##################
# YOUR CODE HERE.#
##################

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[ 0. -1. -2. -3. -4.]
 [ 2.  1.  0. -1. -2.]
 [ 4.  3.  2.  1.  0.]
 [ 6.  5.  4.  3.  2.]
 [ 8.  7.  6.  5.  4.]]


**11.** Considere a matriz

$
X = \begin{bmatrix}
  9 & 3 & 8 \\
  7 & 4 & 5 \\
  2 & 3 & 1 \\
  2 & 10 & 9 \\
  8 & 9 & 2 \\
\end{bmatrix}.
$

Calcule $X_{shifted} = X - \mu$, onde $\mu$ é a média das linhas de $X$. Explore a funcionalidade de broadcasting e não utilize loops.


In [8]:
X = np.array([[9, 3, 8], [7, 4, 5], [2, 3, 1], [2, 10, 9], [8, 9, 2]])
X_shifted = np.zeros(X.shape[1])  # change X_shifted bellow

##################
# YOUR CODE HERE.#
##################

ans = np.array([[3.4, -2.8, 3.0], [1.4, -1.8, 0.0], [-3.6, -2.8, -4.0], [-3.6, 4.2, 4.0], [2.4, 3.2, -3.0]])
are_equal = np.allclose(X_shifted, ans, atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is correct.


**12.** A distância euclidiana entre dois vetores $u$ e $v$ de tamanho $n$ é dada por $\left\|u - v\right\|_2 = \sqrt{\sum_{i=1}^{n}(u_i - v_i)^2}.$

Dado os vetores (1-D arrays) a seguir, complete a função `euclidean_distance` para cálculo da distância. Não utilize loops, nem a função `np.linalg.norm`.

In [61]:
def euclidean_distance(u, v):
    distances = 0
    ##################
    # YOUR CODE HERE.#
    ##################
    return distances


array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

distances = euclidean_distance(array1, array2)
are_equal = np.allclose(distances, np.linalg.norm(array1 - array2), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is not correct.


**13.** Considere duas matrizes $X$ e $Y$, onde cada linha representa um vetor. Você foi solicitado a calcular a distância euclidiana entre as linhas de $X$ e as linhas correspondentes de $Y$. Escreva uma função que recebe as matrizes $X$ e $Y$ como entrada e retorna uma matriz $D$ onde cada elemento $(i,j)$ representa a distância euclidiana entre a linha $i$ de $X$ ($X_i$) e a linha $j$ de $Y$ ($Y_j$). O cálculo deve ser feito por meio de dois loops, conforme a equação

$D_{ij} = \left \|X_i - Y_j \right \|_2$

In [14]:
from scipy.spatial.distance import cdist


def calculate_distances_two_loops(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))
    ##################
    # YOUR CODE HERE.#
    ##################
    return distances


X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

distances = calculate_distances_two_loops(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is not correct.


**14.** O mesmo da questão anterior, mas agora utilizando um loop e broadcasting.

Dica: verifique se o resultado de `X[i] - Y` pode lhe ser útil na solução do exercício.

In [15]:
# Create two 1D numpy array
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

i = 2
print(X[i] - Y)

[[ -9  -9  -9]
 [-12 -12 -12]]


In [16]:
def calculate_distances_one_loop(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))
    ##################
    # YOUR CODE HERE.#
    ##################
    return distances


distances = calculate_distances_one_loop(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is not correct.


**15.** O mesmo da questão anterior, mas agora - você que é um mago do broadcasting - não pode utilizar loops.

Dica: verifique se o resultado de `X[:, np.newaxis, :] - Y` pode lhe ser útil na solução do exercício. 

In [17]:
# Create two 1D numpy array
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

print(X[:, np.newaxis, :] - Y)

[[[-15 -15 -15]
  [-18 -18 -18]]

 [[-12 -12 -12]
  [-15 -15 -15]]

 [[ -9  -9  -9]
  [-12 -12 -12]]

 [[ -6  -6  -6]
  [ -9  -9  -9]]

 [[ -3  -3  -3]
  [ -6  -6  -6]]]


In [18]:
def calculate_distances_vectorized(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))
    ##################
    # YOUR CODE HERE.#
    ##################
    return distances


distances = calculate_distances_one_loop(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is not correct.
